version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - PORT=${PORT}